### ISSUE TITLE
repair fails to recreate intermediate directories

### ISSUE THREAD

**Issue by jcfp** [BlackIkeEagle/par2cmdline#44]
hi,

a bug was filed in Debian concerning an issue with par2repair failing to recreate a missing/deleted directory tree.

The repair process of a recursive parset with 100% redundancy of a file in a nested subdir fails as follows, in case the original directory stucture is missing:
"""
par2repair recovery.par2 
Loading "recovery.par2".
Loaded 4 new packets
Loading "recovery.vol1+2.par2".
Loaded 2 new packets including 2 recovery blocks
Loading "recovery.vol0+1.par2".
Loaded 1 new packets including 1 recovery blocks
Loading "recovery.par2".
No new packets found

There are 1 recoverable files and 0 other files.
The block size used was 4 bytes.
There are a total of 3 data blocks.
The total size of the data files is 12 bytes.

Verifying source files:

Target: "dir1/subdir/file" - missing.

Scanning extra files:

Repair is required.
1 file(s) are missing.
You have 0 out of 3 data blocks available.
You have 3 recovery blocks available.
Repair is possible.
3 recovery blocks will be used to repair.

Could not create: ./dir1/subdir/file
"""

See the original report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781129 for more info.

**Comment by fgouget** [comment]
Hi,

Actually I decided to look into this some more and came up with a patch:
https://github.com/fgouget/par2cmdline/commit/8676db0c366522e2d0b23ee7d6353b7c43e43b0b
It depends on this one which improves error reporting on Unix:
https://github.com/fgouget/par2cmdline/commit/85cd7a9155794a1cfd30c89fca25142378e8fb50

Maybe a pull request would be easier to deal with for you so I'll try to send one (I'm not very used to GitHub).

Cheers,

**Comment by BlackIkeEagle** [comment]
I'll check to merge asap, I just need to free some time and write a test for this bug

**Comment by BlackIkeEagle** [comment]
this got fixed thanks to @fgouget 's pull request #45, thanks
